language: ruby
sudo: false
rvm:
  - 2.1.5
before_script:
  - bundle install
  - npm install
  - npm install -g gulp
script:
  - git config --global user.email "max@maksimize.com"
  - git config --global user.name "Maksim Pecherskiy"
  - gulp publish
  - gulp deploy
cache:
  directories:
  - node_modules
branches:
  only:
    - src
env:
  global:
  - GH_REF: "github.com/mrmaksimize/sdinframap.git"
  - secure: ""
