# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Overrides the default URL, needed for your atom feed and sitemap
url: http://streets.sandiego.gov

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0

source: 'src'
destination: 'serve'


googleTagManager: GTM-M3J864

neek:
  project_id: 58f934e23d5e15299e649061
  write_key: 53AEAF8FF181D3DA531DC59CA3651FB6048153FC60C05664B8DB9BD122B08AFD74723145F87A9070E409C8A78EABFAAF29416BDB9027769416CF160AE759E6F8DADC2AF69B199103B8580C1C19842414A2AE4DB33C587CADD00C63A5D61E940A
